export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'

export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'


export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'

export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'



export const FRIEND_GET_SUCCESS = 'FRIEND_GET_SUCCESS'

export const FRIEND_GET_FAIL = 'FRIEND_GET_FAIL'



export const GET_MESSAGE_REQUEST = 'GET_MESSAGE_REQUEST'

export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS'

export const GET_MESSAGE_FAIL = 'GET_MESSAGE_FAIL'


//export const GET_MESSAGE_REQUEST = 'GET_MESSAGE_REQUEST'

export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS'

export const MESSAGE_SEND_FAIL = 'MESSAGE_SEND_FAIL'



export const IMAGE_MESSAGE_SEND_SUCCESS = 'IMAGE_MESSAGE_SEND_SUCCESS'


export const USER_LOGOUT = 'USER_LOGOUT'